services:
  angular:
    build:
      context: ./frontend
    ports:
      - 8080:80
    networks:
      - bicep
    environment:
      - BACKEND_URL=http://localhost:8000
  grafana:
    build:
      context: ./grafana
    ports:
      - 3000:3000
    networks:
      - bicep
    environment:
      - GF_PATHS_PROVISIONING=/usr/share/grafana/conf/provisioning
  prometheus:
    build:
      context: ./prometheus
    ports: 
      - 9090:9090
    networks:
      - bicep
  prometheus-push-gateway:
    image: prom/pushgateway
    ports: 
      - 9091:9091
    networks:
        - bicep
  core:
    build:
      context: ./backend/core
    volumes:
      - ./backend/core/app:/opt/backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - 8000:8000
    networks:
      - bicep
    environment:
      - DATABASE_URL=bicep-database-1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bicep
      - DATASET_BASE_PATH=/opt
      - PROMETHEUS_URL=prometheus-push-gateway:9091
      - LOKI_URL=http://loki:3100
      - TZ=UTC
      - UVICORN_TIMEOUT_GRACEFUL_SHUTDOWN=600
      - UVICORN_TIMEOUT_KEEP_ALIVE=600

  database:
    build:
      context: ./database
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - bicep
  loki:
    build:
      context: ./loki 
    ports:
      - 3100:3100
    networks:
      - bicep  
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./loki/loki:/mnt/config
    environment:
      - LOG_LEVEL=debug
      - TZ=UTC
networks:
  bicep:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
