services:
  angular:
    build:
      context: ./frontend
    ports:
      - 8080:80
    networks:
      - bicep
    environment:
      - BACKEND_URL=http://core:8000
  grafana:
    build:
      context: ./grafana
    ports:
      - 3000:3000
    networks:
      - bicep
  prometheus:
    build:
      context: ./prometheus
    ports: 
      - 9090:9090
    networks:
      - bicep
  core:
    build:
      context: ./backend/core
    volumes:
      - ./backend/core/app:/opt/backend
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - bicep
    environment:
      - DATABASE_URL=bicep-database-1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bicep
      - PROMETHEUS_URL=prometheus:9090
  database:
    build:
      context: ./database
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - bicep
networks:
  bicep:
    driver: bridge

