auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 10000000000

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

compactor:
  retention_enabled: true
  retention_delete_delay: 1m
  # make this smaller --> are logs then still present !?
  compaction_interval: 1m

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/analytics/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false

# CLI flag: -ingester.per-stream-rate-limit
limits_config:
  per_stream_rate_limit: 10000MB 

  # Maximum burst bytes per stream, also expressible in human readable forms (1MB,
  # 256KB, etc). This is how far above the rate limit a stream can 'burst' before
  # the stream is limited.
  # CLI flag: -ingester.per-stream-rate-limit-burst
  per_stream_rate_limit_burst: 20000MB 

  max_line_size: 5MB
  deletion_mode: filter-and-delete
  retention_period: 1m
  cardinality_limit: 200000
  ingestion_rate_mb: 10000
  max_entries_limit_per_query: 1000000
  ingestion_burst_size_mb: 1000