{
 "title": "BICEP",
 "description": "All metrics regarding the BICEP application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alerts",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{logging=\"alerts\"} |~ `.*`"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "container_cpu_usage != -1", "legendFormat": "{{display_name}}" }
   ]
  },
  {
   "title": "Evaluation metrics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(PRECISION{metric=\"alert-metrics\"}[5h])",
     "legendFormat": "PREC: {{container}}"
    },
    {
     "expr": "last_over_time(FNR{metric=\"alert-metrics\"}[5h])",
     "legendFormat": "FNR: {{container}}"
    },
    {
     "expr": "last_over_time(FPR{metric=\"alert-metrics\"}[5h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(ACCURACY{metric=\"alert-metrics\"}[5h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(F_SCORE{metric=\"alert-metrics\"}[5h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(UNASSIGNED_REQUEST_RATIO{metric=\"alert-metrics\"}[5h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "container_memory_usage != -1", "legendFormat": "{{display_name}}" }
   ]
  }
 ]
}