{
 "title": "BICEP",
 "description": "All metrics regarding the BICEP application",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name!=\"\", name !~\"bicep.*\"} / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage{name != \"\", name !~\"bicep.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{logging=\"alerts\"} |~ `.*`"
    }
   ]
  },
  {
   "title": "Evaluation metrics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "FDR and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "FPR and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "FNR and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "DR and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "ACCURACY and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "PRECISION and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "F_SCORE and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    },
    {
     "expr": "UNASSIGNED_REQUESTS_RATIO and on(exported_job) push_time_seconds >= time() - $__range",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}