{
 "title": "BICEP",
 "description": "All metrics regarding the BICEP application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{logging=~\"alerts\"} |~ `.*`"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "container_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evaluation metrics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{metric=\"alert-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "container_memory_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}