# [Server]

HTTP_ADDRESS 0.0.0.0
HTTP_PORT 8338
USE_SSL false

USERS
    admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:

# [Sensor]

PROCESS_COUNT 1
USE_FEED_UPDATES true
DISABLED_FEEDS turris, ciarmy, policeman, myip, alienvault
IP_MINIMUM_FEEDS 3
UPDATE_PERIOD 86400
CUSTOM_TRAILS_DIR ./trails/custom
CAPTURE_BUFFER 10%
MONITOR_INTERFACE any
CAPTURE_FILTER udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or port 80 or port 1080 or port 3128 or port 8000 or port 8080 or port 8118))
SENSOR_NAME $HOSTNAME
DISABLE_LOCAL_LOG_STORAGE false
USE_HEURISTICS true
CHECK_MISSING_HOST false
CHECK_HOST_DOMAINS false

# [All]

SHOW_DEBUG false
LOG_DIR /opt/logs
