services:
  s1:
    image: busybox
    command: "sleep 10000"
    labels:
      - "bicep.role=SENSOR"
      - "bicep.sensor=true"
      - "bicep.config.mount=/app/config.yaml"
    deploy:
      mode: "replicated"
      replicas: ${S1_SCALE:-1}
  s2:
    image: busybox
    command: "sleep 10001"
    labels:
      - "bicep.role=PIPELINE"
    deploy:
      mode: "replicated"
      replicas: ${S2_SCALE:-1}
